name: Java CI with Maven

on:
  workflow_dispatch:  # 手动触发工作流程
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '10 9 * * *'  # 定时触发工作流程

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar

    - name: Commit files
      run: |
        git config --local user.email "1371016752@qq.com"
        git config --local user.name "jianmo250"
        git pull
        git add README.md
        git add bing-wallpaper.md
        git add picture/*
        git add docs/*
        git commit -m "update readme.md" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BINGWALLPAPER }}
        branch: main
